name: 'PhraseFight2'
version: 0.0.1
description: An absolute bare-bones web app.
author: Derrick Liu <derrick56007@hotmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  force: any
  uuid: any
  stagexl: any

transformers:
- dart_to_js_script_rewriter